// import "./styles/globals.scss";
import "../styles/globals.scss";
import { Barlow, Fraunces } from "next/font/google";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const barlow = Barlow({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-barlow",
});

const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["700", "900"],
  variable: "--font-fraunces",
});

export const metadata = {
  title: "Sunnyside Agency",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`body ${barlow.variable} ${fraunces.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
